version: "3.9"
services:

  http:
    build:
      context: .
      target: http
    ports: 
      -  "8000:8000"
    depends_on:
      - storage
    volumes:
      - "${PWD}/file_records.csv:/file_records.csv"

  storage:
    build:
      context: .
      target: storage
    volumes:
      - "${PWD}/storage:/storage"

volumes:
    fragmo_storage:
    file_records.csv:
